version: '3.1'

services:
  xxl-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    volumes:
      - xxl_admin_log:/data/applogs
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://xxl-db:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=xxl --spring.datasource.password=xxladmin --spring.datasource.driver-class-name=com.mysql.jdbc.Driver"
    ports:
      - 9080:8080
    depends_on:
      - xxl-db
  xxl-job:
    build:
      context: ./xxl-job-executor-sample-springboot
    volumes:
      - xxl_job_log:/data/applogs/xxl-job/jobhandler
    environment:
      PARAMS: "--xxl.job.admin.addresses=http://xxl-admin:8080/xxl-job-admin"
    expose:
      - 8181
    depends_on:
      - xxl-admin
  xxl-db:
    image: mysql:8
    volumes:
      - xxl_db:/var/lib/mysql
    # restart: always
    env_file:
      - ./.db.env
    expose:
      - 3306

volumes:
  xxl_admin_log:
  xxl_job_log:
  xxl_db:
